stages:
  - compile
  - test
  - package

compile:
  stage: compile
  before_script:
    - echo "Hello " > | tr -d "\n" | > file1.txt
    - echo "world" > file2.txt
  script: cat file1.txt file2.txt | grep -q 'Hello world'
  artifacts:
    paths:
    - compiled.txt
    expire_in: 20 minutes

test:
  stage: test
  script: cat compiled.txt | grep -q 'Hello world'

package:
  stage: package
  script: cat compiled.txt | gzip > packaged.gz
  artifacts:
    paths:
    - packaged.gz